# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlexiTable-Example' do
  use_frameworks!

  pod 'FlexiTable', :path => '/Users/Shayne/Documents/Libraries/Swift/FlexiTable'
  #pod 'FlexiTable'

end
